### PR TITLE
Filip d147 patch 1

### PR DESCRIPTION
**Pull request by FilipD147**
Added information to new CLA process using the CLA Assistant

### CODE REVIEW

**Review by EndyCZ — APPROVED** [review]
looks good

**Comment by jpbernius** [comment]
You can also use this link to the CLA:
https://cla-assistant.io/industrial-edge/anomaly-detection-getting-started

**Comment by EndyCZ** [comment]
> You could also use one of these links to the CLA: https://cla-assistant.io/industrial-edge/anomaly-detection-getting-started or https://cla-assistant.io/industrial-edge/

I also thought about that but in the end in every pull request it will automaticaly trigger you that you need to do it. And we would need to add to every repository manualy so probably not worth the effort.

**Comment by EndyCZ** [comment]
Ah I see what you mean. I just noticed your proposal in th other Pull request. I think that make sense to link to general CLA of the indutrial edge organization.  https://cla-assistant.io/industrial-edge/

**Review by HummelN7872 — APPROVED** [review]

**Pull request merged**
